[versions]
activityCompose = "1.9.3"
androidGradlePlugin = "8.7.3"
appcompat = "1.7.0"
coil = "3.0.4"
compiler = "4.12.0"
constraintlayout = "2.2.0"
coreKtx = "1.15.0"
glide = "4.16.0"
junit = "4.13.2"
kotlin = "2.0.20"
leakcanaryAndroid = "2.7"
media = "1.7.0"
media3Exoplayer = "1.5.1"
navigationCompose = "2.8.5"
nexusPublish = "1.1.0"
playlistcore = "2.1.0"
robolectric = "4.13"
composeUi = "1.7.6"
composeMaterial3 = "1.3.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "composeUi" }
compose-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeUi" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
media = { module = "androidx.media:media", version.ref = "media" }
media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3Exoplayer" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3Exoplayer" }
media3-exoplayer-smoothstreaming = { module = "androidx.media3:media3-exoplayer-smoothstreaming", version.ref = "media3Exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
playlistcore = { module = "com.devbrackets.android:playlistcore", version.ref = "playlistcore" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }

